//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//	   如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类实现方法。
// </auto-generated>
//
// <copyright file="WebSiteDbContext">
//		Copyright(c)2018 rights reserved.
//		开 发 者：黄翔宇@中国
//		生成时间：2018-05-09 17:58
// </copyright>
//------------------------------------------------------------------------------
using WebSite.IBLL;
using WebSite.Model.DataBaseModel;

namespace WebSite.BLL
{
    /// <summary>
    /// 实体类-数据表映射——ActionInfo
    /// </summary>  
	public partial class ActionInfoService : BaseService<ActionInfo>, IActionInfoService
	{
		public override void SetCurrentDal()
		{
			CurrentDal = CurrentDbSession.ActionInfoDal;
		}
	}

    /// <summary>
    /// 实体类-数据表映射——ActionInfo_DepartmentInfo
    /// </summary>  
	public partial class ActionInfo_DepartmentInfoService : BaseService<ActionInfo_DepartmentInfo>, IActionInfo_DepartmentInfoService
	{
		public override void SetCurrentDal()
		{
			CurrentDal = CurrentDbSession.ActionInfo_DepartmentInfoDal;
		}
	}

    /// <summary>
    /// 实体类-数据表映射——Category
    /// </summary>  
	public partial class CategoryService : BaseService<Category>, ICategoryService
	{
		public override void SetCurrentDal()
		{
			CurrentDal = CurrentDbSession.CategoryDal;
		}
	}

    /// <summary>
    /// 实体类-数据表映射——DepartmentInfo
    /// </summary>  
	public partial class DepartmentInfoService : BaseService<DepartmentInfo>, IDepartmentInfoService
	{
		public override void SetCurrentDal()
		{
			CurrentDal = CurrentDbSession.DepartmentInfoDal;
		}
	}

    /// <summary>
    /// 实体类-数据表映射——JD_Commodity_001
    /// </summary>  
	public partial class JD_Commodity_001Service : BaseService<JD_Commodity_001>, IJD_Commodity_001Service
	{
		public override void SetCurrentDal()
		{
			CurrentDal = CurrentDbSession.JD_Commodity_001Dal;
		}
	}

    /// <summary>
    /// 实体类-数据表映射——JD_Commodity_002
    /// </summary>  
	public partial class JD_Commodity_002Service : BaseService<JD_Commodity_002>, IJD_Commodity_002Service
	{
		public override void SetCurrentDal()
		{
			CurrentDal = CurrentDbSession.JD_Commodity_002Dal;
		}
	}

    /// <summary>
    /// 实体类-数据表映射——JD_Commodity_003
    /// </summary>  
	public partial class JD_Commodity_003Service : BaseService<JD_Commodity_003>, IJD_Commodity_003Service
	{
		public override void SetCurrentDal()
		{
			CurrentDal = CurrentDbSession.JD_Commodity_003Dal;
		}
	}

    /// <summary>
    /// 实体类-数据表映射——JD_Commodity_004
    /// </summary>  
	public partial class JD_Commodity_004Service : BaseService<JD_Commodity_004>, IJD_Commodity_004Service
	{
		public override void SetCurrentDal()
		{
			CurrentDal = CurrentDbSession.JD_Commodity_004Dal;
		}
	}

    /// <summary>
    /// 实体类-数据表映射——JD_Commodity_005
    /// </summary>  
	public partial class JD_Commodity_005Service : BaseService<JD_Commodity_005>, IJD_Commodity_005Service
	{
		public override void SetCurrentDal()
		{
			CurrentDal = CurrentDbSession.JD_Commodity_005Dal;
		}
	}

    /// <summary>
    /// 实体类-数据表映射——RoleInfo
    /// </summary>  
	public partial class RoleInfoService : BaseService<RoleInfo>, IRoleInfoService
	{
		public override void SetCurrentDal()
		{
			CurrentDal = CurrentDbSession.RoleInfoDal;
		}
	}

    /// <summary>
    /// 实体类-数据表映射——RoleInfo_ActionInfo
    /// </summary>  
	public partial class RoleInfo_ActionInfoService : BaseService<RoleInfo_ActionInfo>, IRoleInfo_ActionInfoService
	{
		public override void SetCurrentDal()
		{
			CurrentDal = CurrentDbSession.RoleInfo_ActionInfoDal;
		}
	}

    /// <summary>
    /// 实体类-数据表映射——RoleInfo_UserInfo
    /// </summary>  
	public partial class RoleInfo_UserInfoService : BaseService<RoleInfo_UserInfo>, IRoleInfo_UserInfoService
	{
		public override void SetCurrentDal()
		{
			CurrentDal = CurrentDbSession.RoleInfo_UserInfoDal;
		}
	}

    /// <summary>
    /// 实体类-数据表映射——UserInfo
    /// </summary>  
	public partial class UserInfoService : BaseService<UserInfo>, IUserInfoService
	{
		public override void SetCurrentDal()
		{
			CurrentDal = CurrentDbSession.UserInfoDal;
		}
	}

    /// <summary>
    /// 实体类-数据表映射——UserInfo_ActionInfo
    /// </summary>  
	public partial class UserInfo_ActionInfoService : BaseService<UserInfo_ActionInfo>, IUserInfo_ActionInfoService
	{
		public override void SetCurrentDal()
		{
			CurrentDal = CurrentDbSession.UserInfo_ActionInfoDal;
		}
	}

    /// <summary>
    /// 实体类-数据表映射——UserInfo_DepartmentInfo
    /// </summary>  
	public partial class UserInfo_DepartmentInfoService : BaseService<UserInfo_DepartmentInfo>, IUserInfo_DepartmentInfoService
	{
		public override void SetCurrentDal()
		{
			CurrentDal = CurrentDbSession.UserInfo_DepartmentInfoDal;
		}
	}

}