//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//	   如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类实现方法。
// </auto-generated>
//
// <copyright file="WebSiteDbContext">
//		Copyright(c)2018 rights reserved.
//		开 发 者：黄翔宇@中国
//		生成时间：2018-05-09 17:58
// </copyright>
//------------------------------------------------------------------------------
using WebSite.IDAL;
using WebSite.Model.DataBaseModel;

namespace WebSite.DAL
{
    /// <summary>
    /// 实体类-数据表映射——ActionInfo
    /// </summary>  
	public partial class ActionInfoDal : BaseDal<ActionInfo>, IActionInfoDal
	{
	}

    /// <summary>
    /// 实体类-数据表映射——ActionInfo_DepartmentInfo
    /// </summary>  
	public partial class ActionInfo_DepartmentInfoDal : BaseDal<ActionInfo_DepartmentInfo>, IActionInfo_DepartmentInfoDal
	{
	}

    /// <summary>
    /// 实体类-数据表映射——Category
    /// </summary>  
	public partial class CategoryDal : BaseDal<Category>, ICategoryDal
	{
	}

    /// <summary>
    /// 实体类-数据表映射——DepartmentInfo
    /// </summary>  
	public partial class DepartmentInfoDal : BaseDal<DepartmentInfo>, IDepartmentInfoDal
	{
	}

    /// <summary>
    /// 实体类-数据表映射——JD_Commodity_001
    /// </summary>  
	public partial class JD_Commodity_001Dal : BaseDal<JD_Commodity_001>, IJD_Commodity_001Dal
	{
	}

    /// <summary>
    /// 实体类-数据表映射——JD_Commodity_002
    /// </summary>  
	public partial class JD_Commodity_002Dal : BaseDal<JD_Commodity_002>, IJD_Commodity_002Dal
	{
	}

    /// <summary>
    /// 实体类-数据表映射——JD_Commodity_003
    /// </summary>  
	public partial class JD_Commodity_003Dal : BaseDal<JD_Commodity_003>, IJD_Commodity_003Dal
	{
	}

    /// <summary>
    /// 实体类-数据表映射——JD_Commodity_004
    /// </summary>  
	public partial class JD_Commodity_004Dal : BaseDal<JD_Commodity_004>, IJD_Commodity_004Dal
	{
	}

    /// <summary>
    /// 实体类-数据表映射——JD_Commodity_005
    /// </summary>  
	public partial class JD_Commodity_005Dal : BaseDal<JD_Commodity_005>, IJD_Commodity_005Dal
	{
	}

    /// <summary>
    /// 实体类-数据表映射——RoleInfo
    /// </summary>  
	public partial class RoleInfoDal : BaseDal<RoleInfo>, IRoleInfoDal
	{
	}

    /// <summary>
    /// 实体类-数据表映射——RoleInfo_ActionInfo
    /// </summary>  
	public partial class RoleInfo_ActionInfoDal : BaseDal<RoleInfo_ActionInfo>, IRoleInfo_ActionInfoDal
	{
	}

    /// <summary>
    /// 实体类-数据表映射——RoleInfo_UserInfo
    /// </summary>  
	public partial class RoleInfo_UserInfoDal : BaseDal<RoleInfo_UserInfo>, IRoleInfo_UserInfoDal
	{
	}

    /// <summary>
    /// 实体类-数据表映射——UserInfo
    /// </summary>  
	public partial class UserInfoDal : BaseDal<UserInfo>, IUserInfoDal
	{
	}

    /// <summary>
    /// 实体类-数据表映射——UserInfo_ActionInfo
    /// </summary>  
	public partial class UserInfo_ActionInfoDal : BaseDal<UserInfo_ActionInfo>, IUserInfo_ActionInfoDal
	{
	}

    /// <summary>
    /// 实体类-数据表映射——UserInfo_DepartmentInfo
    /// </summary>  
	public partial class UserInfo_DepartmentInfoDal : BaseDal<UserInfo_DepartmentInfo>, IUserInfo_DepartmentInfoDal
	{
	}

}