//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//	   如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类定义接口。
// </auto-generated>
//
// <copyright file="WebSiteDbContext">
//		Copyright(c)2018 rights reserved.
//		开 发 者：黄翔宇@中国
//		生成时间：2018-05-09 18:01
// </copyright>
//------------------------------------------------------------------------------
using System.Data.Entity;

namespace WebSite.IDAL
{
	/// <summary>
	/// 业务层调用的是数据会话层的接口。
	/// </summary>
	public partial interface IDbSession
	{
        DbContext DbContext { get; }
        IActionInfoDal ActionInfoDal { get; }
        IActionInfo_DepartmentInfoDal ActionInfo_DepartmentInfoDal { get; }
        ICategoryDal CategoryDal { get; }
        IDepartmentInfoDal DepartmentInfoDal { get; }
        IJD_Commodity_001Dal JD_Commodity_001Dal { get; }
        IJD_Commodity_002Dal JD_Commodity_002Dal { get; }
        IJD_Commodity_003Dal JD_Commodity_003Dal { get; }
        IJD_Commodity_004Dal JD_Commodity_004Dal { get; }
        IJD_Commodity_005Dal JD_Commodity_005Dal { get; }
        IRoleInfoDal RoleInfoDal { get; }
        IRoleInfo_ActionInfoDal RoleInfo_ActionInfoDal { get; }
        IRoleInfo_UserInfoDal RoleInfo_UserInfoDal { get; }
        IUserInfoDal UserInfoDal { get; }
        IUserInfo_ActionInfoDal UserInfo_ActionInfoDal { get; }
        IUserInfo_DepartmentInfoDal UserInfo_DepartmentInfoDal { get; }
      bool SaveChanged();
    }
}