//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//	   如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类定义接口。
// </auto-generated>
//
// <copyright file="WebSiteDbContext">
//		Copyright(c)2018 rights reserved.
//		开 发 者：黄翔宇@中国
//		生成时间：2018-06-15 16:06
// </copyright>
//------------------------------------------------------------------------------
using WebSite.IDAL;
using WebSite.Model.DataBaseModel;

namespace WebSite.IDAL.SingletonPattern
{
    /// <summary>
    /// 实体类-数据表映射——ActionInfo
    /// </summary>  
    public partial interface IActionInfoDal : IBaseDal<ActionInfo>
	{
	}

    /// <summary>
    /// 实体类-数据表映射——ActionInfo_DepartmentInfo
    /// </summary>  
    public partial interface IActionInfo_DepartmentInfoDal : IBaseDal<ActionInfo_DepartmentInfo>
	{
	}

    /// <summary>
    /// 实体类-数据表映射——Category
    /// </summary>  
    public partial interface ICategoryDal : IBaseDal<Category>
	{
	}

    /// <summary>
    /// 实体类-数据表映射——DepartmentInfo
    /// </summary>  
    public partial interface IDepartmentInfoDal : IBaseDal<DepartmentInfo>
	{
	}

    /// <summary>
    /// 实体类-数据表映射——JD_Commodity_001
    /// </summary>  
    public partial interface IJD_Commodity_001Dal : IBaseDal<JD_Commodity_001>
	{
	}

    /// <summary>
    /// 实体类-数据表映射——JD_Commodity_002
    /// </summary>  
    public partial interface IJD_Commodity_002Dal : IBaseDal<JD_Commodity_002>
	{
	}

    /// <summary>
    /// 实体类-数据表映射——JD_Commodity_003
    /// </summary>  
    public partial interface IJD_Commodity_003Dal : IBaseDal<JD_Commodity_003>
	{
	}

    /// <summary>
    /// 实体类-数据表映射——JD_Commodity_004
    /// </summary>  
    public partial interface IJD_Commodity_004Dal : IBaseDal<JD_Commodity_004>
	{
	}

    /// <summary>
    /// 实体类-数据表映射——JD_Commodity_005
    /// </summary>  
    public partial interface IJD_Commodity_005Dal : IBaseDal<JD_Commodity_005>
	{
	}

    /// <summary>
    /// 实体类-数据表映射——KeyWordsRank
    /// </summary>  
    public partial interface IKeyWordsRankDal : IBaseDal<KeyWordsRank>
	{
	}

    /// <summary>
    /// 实体类-数据表映射——RoleInfo
    /// </summary>  
    public partial interface IRoleInfoDal : IBaseDal<RoleInfo>
	{
	}

    /// <summary>
    /// 实体类-数据表映射——RoleInfo_ActionInfo
    /// </summary>  
    public partial interface IRoleInfo_ActionInfoDal : IBaseDal<RoleInfo_ActionInfo>
	{
	}

    /// <summary>
    /// 实体类-数据表映射——RoleInfo_UserInfo
    /// </summary>  
    public partial interface IRoleInfo_UserInfoDal : IBaseDal<RoleInfo_UserInfo>
	{
	}

    /// <summary>
    /// 实体类-数据表映射——SearchDetails
    /// </summary>  
    public partial interface ISearchDetailsDal : IBaseDal<SearchDetails>
	{
	}

    /// <summary>
    /// 实体类-数据表映射——UserInfo
    /// </summary>  
    public partial interface IUserInfoDal : IBaseDal<UserInfo>
	{
	}

    /// <summary>
    /// 实体类-数据表映射——UserInfo_ActionInfo
    /// </summary>  
    public partial interface IUserInfo_ActionInfoDal : IBaseDal<UserInfo_ActionInfo>
	{
	}

    /// <summary>
    /// 实体类-数据表映射——UserInfo_DepartmentInfo
    /// </summary>  
    public partial interface IUserInfo_DepartmentInfoDal : IBaseDal<UserInfo_DepartmentInfo>
	{
	}

}