//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//	   如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类定义接口。
// </auto-generated>
//
// <copyright file="WebSiteDbContext">
//		Copyright(c)2018 rights reserved.
//		开 发 者：黄翔宇@中国
//		生成时间：2018-06-15 16:18
// </copyright>
//------------------------------------------------------------------------------
using WebSite.Model.DataBaseModel;

namespace WebSite.IBLL.SingletonPattern
{
    /// <summary>
    /// 实体类-数据表映射——ActionInfo
    /// </summary>  
	public partial interface IActionInfoService : IBaseService<ActionInfo>
	{
	}

    /// <summary>
    /// 实体类-数据表映射——ActionInfo_DepartmentInfo
    /// </summary>  
	public partial interface IActionInfo_DepartmentInfoService : IBaseService<ActionInfo_DepartmentInfo>
	{
	}

    /// <summary>
    /// 实体类-数据表映射——Category
    /// </summary>  
	public partial interface ICategoryService : IBaseService<Category>
	{
	}

    /// <summary>
    /// 实体类-数据表映射——DepartmentInfo
    /// </summary>  
	public partial interface IDepartmentInfoService : IBaseService<DepartmentInfo>
	{
	}

    /// <summary>
    /// 实体类-数据表映射——JD_Commodity_001
    /// </summary>  
	public partial interface IJD_Commodity_001Service : IBaseService<JD_Commodity_001>
	{
	}

    /// <summary>
    /// 实体类-数据表映射——JD_Commodity_002
    /// </summary>  
	public partial interface IJD_Commodity_002Service : IBaseService<JD_Commodity_002>
	{
	}

    /// <summary>
    /// 实体类-数据表映射——JD_Commodity_003
    /// </summary>  
	public partial interface IJD_Commodity_003Service : IBaseService<JD_Commodity_003>
	{
	}

    /// <summary>
    /// 实体类-数据表映射——JD_Commodity_004
    /// </summary>  
	public partial interface IJD_Commodity_004Service : IBaseService<JD_Commodity_004>
	{
	}

    /// <summary>
    /// 实体类-数据表映射——JD_Commodity_005
    /// </summary>  
	public partial interface IJD_Commodity_005Service : IBaseService<JD_Commodity_005>
	{
	}

    /// <summary>
    /// 实体类-数据表映射——KeyWordsRank
    /// </summary>  
	public partial interface IKeyWordsRankService : IBaseService<KeyWordsRank>
	{
	}

    /// <summary>
    /// 实体类-数据表映射——RoleInfo
    /// </summary>  
	public partial interface IRoleInfoService : IBaseService<RoleInfo>
	{
	}

    /// <summary>
    /// 实体类-数据表映射——RoleInfo_ActionInfo
    /// </summary>  
	public partial interface IRoleInfo_ActionInfoService : IBaseService<RoleInfo_ActionInfo>
	{
	}

    /// <summary>
    /// 实体类-数据表映射——RoleInfo_UserInfo
    /// </summary>  
	public partial interface IRoleInfo_UserInfoService : IBaseService<RoleInfo_UserInfo>
	{
	}

    /// <summary>
    /// 实体类-数据表映射——SearchDetails
    /// </summary>  
	public partial interface ISearchDetailsService : IBaseService<SearchDetails>
	{
	}

    /// <summary>
    /// 实体类-数据表映射——UserInfo
    /// </summary>  
	public partial interface IUserInfoService : IBaseService<UserInfo>
	{
	}

    /// <summary>
    /// 实体类-数据表映射——UserInfo_ActionInfo
    /// </summary>  
	public partial interface IUserInfo_ActionInfoService : IBaseService<UserInfo_ActionInfo>
	{
	}

    /// <summary>
    /// 实体类-数据表映射——UserInfo_DepartmentInfo
    /// </summary>  
	public partial interface IUserInfo_DepartmentInfoService : IBaseService<UserInfo_DepartmentInfo>
	{
	}

}